POST http://localhost:8081/api/auth/login
Content-Type: application/json

{"username": "user", "password": "user"}

> {% client.global.set("auth_token", response.headers.valueOf("Authorization")); %}

###
POST http://localhost:8081/api/service/operations
Authorization: {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "monnaieSource": "USD",
  "monnaieDestination" : "EUR",
  "taux": "1.2",
  "montant" : "1600"
}
###
POST http://localhost:8081/api/service/operations
Authorization: {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "monnaieSource": "USD",
  "monnaieDestination" : "EUR",
  "taux": "1.2",
  "montant" : "7900"
}
###
POST http://localhost:8081/api/service/operations
Authorization: {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "monnaieSource": "USD",
  "monnaieDestination" : "EUR",
  "taux": "1.2",
  "montant" : "8900"
}
###
POST http://localhost:8081/api/service/operations
Authorization: {{auth_token}}
Content-Type: application/json
Accept: application/json

{
  "monnaieSource": "DZA",
  "monnaieDestination" : "EUR",
  "taux": "0.4",
  "montant" : "1000"
}
###

GET http://localhost:8081/api/service/operations

###
PUT http://localhost:8081/api/service/operations
Authorization: {{auth_token}}
Content-Type: application/json
Accept: application/json

{"id_transaction" : 1,
  "monnaieSource": "USD",
  "monnaieDestination" : "EUR",
  "taux": "1.2",
  "montant" : "200"
}
###
GET http://localhost:8081/api/service/operationsHistory?dest=EUR&source=USD

###
GET http://localhost:8081/api/service/operations/1

###
DELETE http://localhost:8081/api/service/operations/1

###
GET http://localhost:8081/api/service/operations